{{- $existingSecret := lookup "v1" "Secret" "maas-api-keys" "api-key-test-user" }}
apiVersion: v1
kind: Secret
metadata:
  name: api-key-test-user
  namespace: maas-api-keys
  labels:
    authorino.kuadrant.io/managed-by: authorino
  annotations:
    user.authorino.kuadrant.io/userid: "maas-user"
    user.authorino.kuadrant.io/groups: "tier-premium-users"
    sync.argoproj.io/sync-wave: "1"
type: Opaque
{{- if $existingSecret }}
data:
  # Use existing secret data
  api_key: {{ index $existingSecret.data "api_key" }}
{{- else }}
stringData:
  # Generate new secret only if it doesn't exist
  api_key: "{{ randAlphaNum 20 }}"
{{- end }}
