apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-user-llminferenceservice-access-binding
  namespace: llm
subjects:
  - kind: User
    name: test-user  # The userid from your API key secret annotation
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: llminferenceservice-access
  apiGroup: rbac.authorization.k8s.io
