apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    openshift.io/display-name: granite-3-3-8b
    alpha.maas.opendatahub.io/tiers: '[]'
    argocd.argoproj.io/sync-wave: "2"
  name: granite-3-3-8b
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  model:
    name: granite-3-3-8b
    uri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.3-2b-instruct'
  replicas: 1
  router:
    route: { }
    # Connect to MaaS-enabled gateway
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
  template:
    # Ensure the pod is scheduled on GPU nodes
    nodeSelector:
      nvidia.com/gpu.present: "true"
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    containers:
      - image: 'registry.redhat.io/rhoai/odh-vllm-cpu-rhel9@sha256:bae57975dfe153afc799e868e6a27ec1e502f68d4337a74dc6455a6bc326d02c'
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
        name: main
        resources:
          limits:
            cpu: '2'
            memory: 12Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '500m'
            memory: 8Gi
            nvidia.com/gpu: '1'