apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: granite-8b-code-instruct
  namepace: llm
  annotations:
    openshift.io/display-name: granite-8b-code-instruct
    alpha.maas.opendatahub.io/tiers: '[]'
    argocd.argoproj.io/sync-wave: "2"
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  model:
    name: granite-8b-code-instruct
    uri: 'oci://registry.redhat.io/rhelai1/modelcar-granite-8b-code-instruct:1.4'
  replicas: 1
  router:
    route: { }
    # Connect to MaaS-enabled gateway
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
  template:
    # Ensure the pod is scheduled on GPU nodes
    nodeSelector:
      nvidia.com/gpu.present: "true"
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    containers:
    - name: main
      resources:
        limits:
          cpu: '2'
          memory: 12Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '500m'
          memory: 8Gi
          nvidia.com/gpu: '1'