apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redhat-connectivity-link
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: ./charts/redhat-connectivity-link
    helm:
      parameters:
        - name: operator.channel
          value: {{ .Values.redhatConnectivityLink.operator.channel }}
        - name: operator.installPlanApproval
          value: {{ .Values.redhatConnectivityLink.operator.installPlanApproval }}
        - name: operator.startingCSV
          value: {{ .Values.redhatConnectivityLink.operator.startingCSV }}
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name | contains("-dockercfg-"))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 2m # the maximum amount of time allowed for the backoff strategy