{{- range .Values.apiUsers }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .username }}-llminferenceservice-access-binding
  namespace: llm
subjects:
  - kind: User
    name: {{ .username }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: llminferenceservice-access
  apiGroup: rbac.authorization.k8s.io
{{- end }}
